version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=reviews
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build: ./
    ports:
      - 8100:8100
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
