USE reviews;
CREATE TABLE tbl_product
(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME CHAR(100),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tbl_review
(
    ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODUCT_ID)
        REFERENCES tbl_product(ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tbl_comment
(
    ID INT NOT NULL AUTO_INCREMENT,
    REVIEW_ID INT NOT NULL,
    REVIEW_COMMENT CHAR(255) DEFAULT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (REVIEW_ID)
        REFERENCES tbl_review(ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;